# Generated by Django 2.2 on 2019-05-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=40)),
                ('default_activation', models.TimeField()),
                ('default_break', models.TimeField()),
                ('default_set', models.IntegerField()),
                ('default_calorie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_time', models.TimeField()),
                ('break_time', models.TimeField()),
                ('train_set', models.IntegerField()),
                ('calorie_consumption', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.TrainInfo')),
            ],
        ),
    ]
