# Generated by Django 2.2.1 on 2019-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
