# Generated by Django 2.2.1 on 2019-05-11 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('train', '0002_auto_20190510_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=40)),
                ('default_activation', models.TimeField()),
                ('default_break', models.TimeField()),
                ('default_set', models.IntegerField()),
                ('default_calorie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_date', models.DateField(auto_now_add=True)),
                ('activation_time', models.TimeField()),
                ('break_time', models.TimeField()),
                ('train_set', models.IntegerField()),
                ('calorie_consumption', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.TrainInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
