# Generated by Django 2.2 on 2019-05-19 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_trainresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainresult',
            name='train_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
