# Generated by Django 2.2 on 2019-05-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20190511_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainresult',
            name='train_date',
        ),
    ]
