# Generated by Django 2.2.1 on 2019-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
