# Generated by Django 2.2 on 2019-05-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=200)),
                ('user_preference', models.ManyToManyField(to='train.TrainInfo')),
                ('user_result', models.ManyToManyField(related_name='user_traininfo_fk', through='train.TrainResult', to='train.TrainInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.User')),
                ('user_sex', models.BooleanField()),
                ('user_birthdate', models.DateField()),
                ('user_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('user_height', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
