# Generated by Django 2.2 on 2019-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190514_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sex', models.BooleanField()),
                ('user_birthdate', models.DateField()),
                ('user_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('user_height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('user_smoking', models.BooleanField()),
            ],
        ),
    ]
