# Generated by Django 2.2 on 2019-05-15 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_remove_trainresult_train_date'),
        ('user', '0003_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_preference',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='train.TrainInfo'),
            preserve_default=False,
        ),
    ]
